import type { StripBackground, BackgroundCategory } from '@/types'

export const BACKGROUND_CATEGORIES: { id: BackgroundCategory; label: string }[] = [
  { id: 'aesthetic', label: 'Aesthetic' },
  { id: 'gradient', label: 'Gradient' },
  { id: 'pattern', label: 'Pattern' },
  { id: 'vibrant', label: 'Vibrant' },
  { id: 'dark', label: 'Dark' },
  { id: 'retro', label: 'Retro' },
  { id: 'nature', label: 'Nature' },
  { id: 'seasonal', label: 'Seasonal' },
]

export const BACKGROUNDS: StripBackground[] = [
  // ── Aesthetic ──────────────────────────────────────────────────────────────
  {
    id: 'blush-pink',
    name: 'Blush Pink',
    description: 'Soft pink aesthetic',
    type: 'solid',
    value: '#fbd3e9',
    previewColor: '#fbd3e9',
    category: 'aesthetic',
    emoji: '🌸',
  },
  {
    id: 'cream',
    name: 'Cream',
    description: 'Warm creamy white',
    type: 'solid',
    value: '#fef7f0',
    previewColor: '#fef7f0',
    category: 'aesthetic',
    emoji: '☕',
  },
  {
    id: 'lavender-mist',
    name: 'Lavender Mist',
    description: 'Soft purple aesthetic',
    type: 'solid',
    value: '#e8d9f0',
    previewColor: '#e8d9f0',
    category: 'aesthetic',
    emoji: '💜',
  },
  {
    id: 'sage-green',
    name: 'Sage Green',
    description: 'Calm muted green',
    type: 'solid',
    value: '#c8dcc4',
    previewColor: '#c8dcc4',
    category: 'aesthetic',
    emoji: '🌿',
  },
  {
    id: 'powder-blue',
    name: 'Powder Blue',
    description: 'Soft sky blue',
    type: 'solid',
    value: '#d4e4f7',
    previewColor: '#d4e4f7',
    category: 'aesthetic',
    emoji: '☁️',
  },
  {
    id: 'rose-quartz',
    name: 'Rose Quartz',
    description: 'Dusty rose tone',
    type: 'solid',
    value: '#f4c2c2',
    previewColor: '#f4c2c2',
    category: 'aesthetic',
    emoji: '�',
  },
  {
    id: 'baby-yellow',
    name: 'Baby Yellow',
    description: 'Soft pastel yellow',
    type: 'solid',
    value: '#fff9c4',
    previewColor: '#fff9c4',
    category: 'aesthetic',
    emoji: '�',
  },
  {
    id: 'mint-cream',
    name: 'Mint Cream',
    description: 'Fresh mint pastel',
    type: 'solid',
    value: '#c8f0e0',
    previewColor: '#c8f0e0',
    category: 'aesthetic',
    emoji: '�',
  },
  {
    id: 'lilac',
    name: 'Lilac',
    description: 'Dreamy lilac purple',
    type: 'solid',
    value: '#d8b4fe',
    previewColor: '#d8b4fe',
    category: 'aesthetic',
    emoji: '🪻',
  },
  {
    id: 'peach-fuzz',
    name: 'Peach Fuzz',
    description: 'Warm peachy tone',
    type: 'solid',
    value: '#ffcba4',
    previewColor: '#ffcba4',
    category: 'aesthetic',
    emoji: '�',
  },

  // ── Gradient ───────────────────────────────────────────────────────────────
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm sunset gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ffb347 0%, #ffdbac 50%, #ffd699 100%)',
    previewColor: '#ffb347',
    category: 'gradient',
    emoji: '🌅',
  },
  {
    id: 'ocean-wave',
    name: 'Ocean Wave',
    description: 'Serene ocean gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    previewColor: '#667eea',
    category: 'gradient',
    emoji: '🌊',
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    description: 'Sweet pink-blue gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ffc0e3 0%, #c4a8ff 50%, #a3c5ff 100%)',
    previewColor: '#ffc0e3',
    category: 'gradient',
    emoji: '🍭',
  },
  {
    id: 'peach-dream',
    name: 'Peach Dream',
    description: 'Warm peach gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ffd89b 0%, #ffb6a3 50%, #ff9fb2 100%)',
    previewColor: '#ffd89b',
    category: 'gradient',
    emoji: '🍑',
  },
  {
    id: 'minty-fresh',
    name: 'Minty Fresh',
    description: 'Cool mint gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 50%, #fed6e3 100%)',
    previewColor: '#a8edea',
    category: 'gradient',
    emoji: '🌬️',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Rich golden gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #f6d5a8 0%, #f9a825 50%, #f97316 100%)',
    previewColor: '#f6d5a8',
    category: 'gradient',
    emoji: '✨',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Northern lights gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #00c9a7 0%, #845ec2 50%, #ff6f91 100%)',
    previewColor: '#00c9a7',
    category: 'gradient',
    emoji: '🌌',
  },
  {
    id: 'rose-gold',
    name: 'Rose Gold',
    description: 'Elegant rose gold gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #f9c5d1 0%, #e8a0b4 50%, #c97b8a 100%)',
    previewColor: '#f9c5d1',
    category: 'gradient',
    emoji: '💅',
  },
  {
    id: 'tropical',
    name: 'Tropical',
    description: 'Vibrant tropical gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #f7971e 0%, #ffd200 50%, #21d4fd 100%)',
    previewColor: '#f7971e',
    category: 'gradient',
    emoji: '🌴',
  },
  {
    id: 'galaxy',
    name: 'Galaxy',
    description: 'Deep space gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    previewColor: '#302b63',
    category: 'gradient',
    emoji: '🔭',
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    description: 'Soft sakura gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 50%, #ff9a9e 100%)',
    previewColor: '#ffecd2',
    category: 'gradient',
    emoji: '🌸',
  },
  {
    id: 'deep-sea',
    name: 'Deep Sea',
    description: 'Dark ocean gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    previewColor: '#203a43',
    category: 'gradient',
    emoji: '🐋',
  },

  // ── Pattern ────────────────────────────────────────────────────────────────
  {
    id: 'polka-pink',
    name: 'Polka Pink',
    description: 'Pink with white polka dots',
    type: 'pattern',
    value: 'radial-gradient(circle, #ffffff 2px, transparent 2px), linear-gradient(0deg, #ffc0e3, #ffc0e3)',
    previewColor: '#ffc0e3',
    category: 'pattern',
    emoji: '⚪',
  },
  {
    id: 'checkerboard',
    name: 'Checkerboard',
    description: 'Classic checkerboard pattern',
    type: 'pattern',
    value: 'linear-gradient(45deg, #e0e0e0 25%, transparent 25%, transparent 75%, #e0e0e0 75%, #e0e0e0), linear-gradient(45deg, #e0e0e0 25%, transparent 25%, transparent 75%, #e0e0e0 75%, #e0e0e0), linear-gradient(#f5f5f5, #f5f5f5)',
    previewColor: '#f5f5f5',
    category: 'pattern',
    emoji: '🏁',
  },
  {
    id: 'diagonal-stripes',
    name: 'Diagonal Stripes',
    description: 'Soft diagonal stripes',
    type: 'pattern',
    value: 'repeating-linear-gradient(45deg, #f0e6ff, #f0e6ff 10px, #e6d9ff 10px, #e6d9ff 20px)',
    previewColor: '#f0e6ff',
    category: 'pattern',
    emoji: '🎀',
  },
  {
    id: 'wavy-lines',
    name: 'Wavy Lines',
    description: 'Subtle wavy pattern',
    type: 'pattern',
    value: 'linear-gradient(0deg, rgba(200,220,196,0.3) 0%, transparent 50%, rgba(200,220,196,0.3) 100%)',
    previewColor: '#f0f8f0',
    category: 'pattern',
    emoji: '〰️',
  },
  {
    id: 'polka-blue',
    name: 'Polka Blue',
    description: 'Blue with white polka dots',
    type: 'pattern',
    value: 'radial-gradient(circle, #ffffff 2px, transparent 2px), linear-gradient(0deg, #a3c5ff, #a3c5ff)',
    previewColor: '#a3c5ff',
    category: 'pattern',
    emoji: '🔵',
  },
  {
    id: 'grid-lines',
    name: 'Grid Lines',
    description: 'Soft grid pattern',
    type: 'pattern',
    value: 'linear-gradient(rgba(180,180,220,0.4) 1px, transparent 1px), linear-gradient(90deg, rgba(180,180,220,0.4) 1px, transparent 1px), linear-gradient(#f8f8ff, #f8f8ff)',
    previewColor: '#f8f8ff',
    category: 'pattern',
    emoji: '📐',
  },
  {
    id: 'horizontal-stripes',
    name: 'H-Stripes',
    description: 'Horizontal pastel stripes',
    type: 'pattern',
    value: 'repeating-linear-gradient(0deg, #ffd6e7, #ffd6e7 12px, #fff0f6 12px, #fff0f6 24px)',
    previewColor: '#ffd6e7',
    category: 'pattern',
    emoji: '🎌',
  },
  {
    id: 'dots-yellow',
    name: 'Sunny Dots',
    description: 'Yellow polka dot pattern',
    type: 'pattern',
    value: 'radial-gradient(circle, #ffffff 2px, transparent 2px), linear-gradient(0deg, #fff176, #fff176)',
    previewColor: '#fff176',
    category: 'pattern',
    emoji: '🌻',
  },
  {
    id: 'zigzag',
    name: 'Zigzag',
    description: 'Fun zigzag pattern',
    type: 'pattern',
    value: 'repeating-linear-gradient(120deg, #fce4ec, #fce4ec 10px, #f8bbd0 10px, #f8bbd0 20px, #fce4ec 20px)',
    previewColor: '#fce4ec',
    category: 'pattern',
    emoji: '⚡',
  },

  // ── Vibrant ────────────────────────────────────────────────────────────────
  {
    id: 'neon-pink',
    name: 'Neon Pink',
    description: 'Bright electric pink',
    type: 'solid',
    value: '#ff006e',
    previewColor: '#ff006e',
    category: 'vibrant',
    emoji: '💖',
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    description: 'Vibrant neon blue',
    type: 'solid',
    value: '#00d9ff',
    previewColor: '#00d9ff',
    category: 'vibrant',
    emoji: '⚡',
  },
  {
    id: 'lime-green',
    name: 'Lime Green',
    description: 'Bright lime accent',
    type: 'solid',
    value: '#39ff14',
    previewColor: '#39ff14',
    category: 'vibrant',
    emoji: '💚',
  },
  {
    id: 'hot-orange',
    name: 'Hot Orange',
    description: 'Fiery orange',
    type: 'solid',
    value: '#ff6b35',
    previewColor: '#ff6b35',
    category: 'vibrant',
    emoji: '🔥',
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    description: 'Deep royal purple',
    type: 'solid',
    value: '#7209b7',
    previewColor: '#7209b7',
    category: 'vibrant',
    emoji: '👑',
  },
  {
    id: 'cyber-gradient',
    name: 'Cyber',
    description: 'Neon cyber gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ff006e 0%, #00d9ff 50%, #39ff14 100%)',
    previewColor: '#ff006e',
    category: 'vibrant',
    emoji: '🌐',
  },
  {
    id: 'hot-coral',
    name: 'Hot Coral',
    description: 'Vivid coral red',
    type: 'solid',
    value: '#ff4757',
    previewColor: '#ff4757',
    category: 'vibrant',
    emoji: '🪸',
  },
  {
    id: 'vivid-teal',
    name: 'Vivid Teal',
    description: 'Bold teal green',
    type: 'solid',
    value: '#00b894',
    previewColor: '#00b894',
    category: 'vibrant',
    emoji: '🦚',
  },
  {
    id: 'magenta-burst',
    name: 'Magenta Burst',
    description: 'Bright magenta gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #f953c6 0%, #b91d73 100%)',
    previewColor: '#f953c6',
    category: 'vibrant',
    emoji: '💥',
  },
  {
    id: 'acid-yellow',
    name: 'Acid Yellow',
    description: 'Neon yellow pop',
    type: 'solid',
    value: '#f9f900',
    previewColor: '#f9f900',
    category: 'vibrant',
    emoji: '🟡',
  },

  // ── Dark ───────────────────────────────────────────────────────────────────
  {
    id: 'midnight-black',
    name: 'Midnight',
    description: 'Pure deep black',
    type: 'solid',
    value: '#0a0a0a',
    previewColor: '#0a0a0a',
    category: 'dark',
    emoji: '🌑',
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    description: 'Dark charcoal grey',
    type: 'solid',
    value: '#2d2d2d',
    previewColor: '#2d2d2d',
    category: 'dark',
    emoji: '🪨',
  },
  {
    id: 'dark-navy',
    name: 'Dark Navy',
    description: 'Deep navy blue',
    type: 'solid',
    value: '#0d1b2a',
    previewColor: '#0d1b2a',
    category: 'dark',
    emoji: '🌃',
  },
  {
    id: 'dark-forest',
    name: 'Dark Forest',
    description: 'Deep forest green',
    type: 'solid',
    value: '#1a2e1a',
    previewColor: '#1a2e1a',
    category: 'dark',
    emoji: '🌲',
  },
  {
    id: 'dark-wine',
    name: 'Dark Wine',
    description: 'Deep burgundy red',
    type: 'solid',
    value: '#3b0a1f',
    previewColor: '#3b0a1f',
    category: 'dark',
    emoji: '🍷',
  },
  {
    id: 'dark-gradient',
    name: 'Dark Fade',
    description: 'Dark moody gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    previewColor: '#1a1a2e',
    category: 'dark',
    emoji: '🌙',
  },
  {
    id: 'dark-purple',
    name: 'Dark Violet',
    description: 'Deep violet darkness',
    type: 'solid',
    value: '#1a0533',
    previewColor: '#1a0533',
    category: 'dark',
    emoji: '🔮',
  },
  {
    id: 'dark-smoke',
    name: 'Smoke',
    description: 'Smoky dark grey',
    type: 'gradient',
    value: 'linear-gradient(135deg, #373b44 0%, #4286f4 100%)',
    previewColor: '#373b44',
    category: 'dark',
    emoji: '💨',
  },

  // ── Retro ──────────────────────────────────────────────────────────────────
  {
    id: 'retro-orange',
    name: 'Retro Orange',
    description: '70s warm orange',
    type: 'solid',
    value: '#e8a87c',
    previewColor: '#e8a87c',
    category: 'retro',
    emoji: '📻',
  },
  {
    id: 'retro-yellow',
    name: 'Retro Yellow',
    description: 'Vintage mustard yellow',
    type: 'solid',
    value: '#d4a017',
    previewColor: '#d4a017',
    category: 'retro',
    emoji: '🎞️',
  },
  {
    id: 'retro-teal',
    name: 'Retro Teal',
    description: 'Vintage teal green',
    type: 'solid',
    value: '#4a9e8e',
    previewColor: '#4a9e8e',
    category: 'retro',
    emoji: '📺',
  },
  {
    id: 'retro-pink',
    name: 'Retro Pink',
    description: '80s hot pink',
    type: 'solid',
    value: '#e75480',
    previewColor: '#e75480',
    category: 'retro',
    emoji: '🕹️',
  },
  {
    id: 'sepia',
    name: 'Sepia',
    description: 'Classic sepia tone',
    type: 'solid',
    value: '#c4a882',
    previewColor: '#c4a882',
    category: 'retro',
    emoji: '📷',
  },
  {
    id: 'retro-gradient',
    name: 'Retro Sunset',
    description: '80s retro gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #fc5c7d 0%, #6a3093 100%)',
    previewColor: '#fc5c7d',
    category: 'retro',
    emoji: '🌆',
  },
  {
    id: 'vhs-blue',
    name: 'VHS Blue',
    description: 'Old VHS tape blue',
    type: 'gradient',
    value: 'linear-gradient(135deg, #1a1a4e 0%, #2d2d8e 50%, #1a1a4e 100%)',
    previewColor: '#2d2d8e',
    category: 'retro',
    emoji: '📼',
  },

  // ── Nature ─────────────────────────────────────────────────────────────────
  {
    id: 'forest-green',
    name: 'Forest',
    description: 'Deep forest green',
    type: 'solid',
    value: '#2d6a4f',
    previewColor: '#2d6a4f',
    category: 'nature',
    emoji: '🌳',
  },
  {
    id: 'sky-blue',
    name: 'Sky Blue',
    description: 'Clear daytime sky',
    type: 'solid',
    value: '#87ceeb',
    previewColor: '#87ceeb',
    category: 'nature',
    emoji: '☀️',
  },
  {
    id: 'earth-brown',
    name: 'Earth',
    description: 'Warm earthy brown',
    type: 'solid',
    value: '#8b6914',
    previewColor: '#8b6914',
    category: 'nature',
    emoji: '🌍',
  },
  {
    id: 'ocean-blue',
    name: 'Ocean',
    description: 'Deep ocean blue',
    type: 'solid',
    value: '#006994',
    previewColor: '#006994',
    category: 'nature',
    emoji: '🌊',
  },
  {
    id: 'sunset-nature',
    name: 'Sunset Sky',
    description: 'Natural sunset colors',
    type: 'gradient',
    value: 'linear-gradient(180deg, #ff7e5f 0%, #feb47b 50%, #ffcba4 100%)',
    previewColor: '#ff7e5f',
    category: 'nature',
    emoji: '🌄',
  },
  {
    id: 'meadow',
    name: 'Meadow',
    description: 'Fresh green meadow',
    type: 'gradient',
    value: 'linear-gradient(180deg, #87ceeb 0%, #87ceeb 40%, #7ec850 40%, #5a9e3a 100%)',
    previewColor: '#7ec850',
    category: 'nature',
    emoji: '🌾',
  },
  {
    id: 'sand',
    name: 'Sandy Beach',
    description: 'Warm sandy tone',
    type: 'solid',
    value: '#f4d9a0',
    previewColor: '#f4d9a0',
    category: 'nature',
    emoji: '🏖️',
  },
  {
    id: 'stone-grey',
    name: 'Stone',
    description: 'Natural stone grey',
    type: 'solid',
    value: '#9e9e9e',
    previewColor: '#9e9e9e',
    category: 'nature',
    emoji: '🪨',
  },

  // ── Seasonal ───────────────────────────────────────────────────────────────
  {
    id: 'spring-bloom',
    name: 'Spring Bloom',
    description: 'Fresh spring colors',
    type: 'gradient',
    value: 'linear-gradient(135deg, #f9d4e8 0%, #c8f0c8 50%, #d4e8f9 100%)',
    previewColor: '#f9d4e8',
    category: 'seasonal',
    emoji: '🌷',
  },
  {
    id: 'summer-vibes',
    name: 'Summer Vibes',
    description: 'Bright summer gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #f9d423 0%, #ff4e50 100%)',
    previewColor: '#f9d423',
    category: 'seasonal',
    emoji: '☀️',
  },
  {
    id: 'autumn-leaves',
    name: 'Autumn Leaves',
    description: 'Warm autumn tones',
    type: 'gradient',
    value: 'linear-gradient(135deg, #d4380d 0%, #fa8c16 50%, #fadb14 100%)',
    previewColor: '#d4380d',
    category: 'seasonal',
    emoji: '🍂',
  },
  {
    id: 'winter-frost',
    name: 'Winter Frost',
    description: 'Cool icy winter',
    type: 'gradient',
    value: 'linear-gradient(135deg, #e0f7fa 0%, #b2ebf2 50%, #e8eaf6 100%)',
    previewColor: '#e0f7fa',
    category: 'seasonal',
    emoji: '❄️',
  },
  {
    id: 'halloween',
    name: 'Halloween',
    description: 'Spooky orange and black',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ff6600 0%, #1a0a00 100%)',
    previewColor: '#ff6600',
    category: 'seasonal',
    emoji: '🎃',
  },
  {
    id: 'christmas',
    name: 'Christmas',
    description: 'Festive red and green',
    type: 'gradient',
    value: 'linear-gradient(135deg, #c0392b 0%, #27ae60 100%)',
    previewColor: '#c0392b',
    category: 'seasonal',
    emoji: '🎄',
  },
  {
    id: 'new-year',
    name: 'New Year',
    description: 'Glittery celebration',
    type: 'gradient',
    value: 'linear-gradient(135deg, #1a1a2e 0%, #c9a84c 50%, #1a1a2e 100%)',
    previewColor: '#c9a84c',
    category: 'seasonal',
    emoji: '🎆',
  },
  {
    id: 'valentines',
    name: "Valentine's",
    description: 'Romantic pink and red',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ff6b9d 0%, #c44569 50%, #f8b500 100%)',
    previewColor: '#ff6b9d',
    category: 'seasonal',
    emoji: '💝',
  },
]
