import type { StripBackground, BackgroundCategory } from '@/types'

export const BACKGROUND_CATEGORIES: { id: BackgroundCategory; label: string }[] = [
  { id: 'aesthetic', label: 'Aesthetic' },
  { id: 'gradient', label: 'Gradient' },
  { id: 'pattern', label: 'Pattern' },
  { id: 'vibrant', label: 'Vibrant' },
]

export const BACKGROUNDS: StripBackground[] = [
  // Aesthetic Backgrounds
  {
    id: 'blush-pink',
    name: 'Blush Pink',
    description: 'Soft pink aesthetic',
    type: 'solid',
    value: '#fbd3e9',
    previewColor: '#fbd3e9',
    category: 'aesthetic',
    emoji: '🌸',
  },
  {
    id: 'cream',
    name: 'Cream',
    description: 'Warm creamy white',
    type: 'solid',
    value: '#fef7f0',
    previewColor: '#fef7f0',
    category: 'aesthetic',
    emoji: '☕',
  },
  {
    id: 'lavender-mist',
    name: 'Lavender Mist',
    description: 'Soft purple aesthetic',
    type: 'solid',
    value: '#e8d9f0',
    previewColor: '#e8d9f0',
    category: 'aesthetic',
    emoji: '💜',
  },
  {
    id: 'sage-green',
    name: 'Sage Green',
    description: 'Calm muted green',
    type: 'solid',
    value: '#c8dcc4',
    previewColor: '#c8dcc4',
    category: 'aesthetic',
    emoji: '🌿',
  },
  {
    id: 'powder-blue',
    name: 'Powder Blue',
    description: 'Soft sky blue',
    type: 'solid',
    value: '#d4e4f7',
    previewColor: '#d4e4f7',
    category: 'aesthetic',
    emoji: '☁️',
  },

  // Gradient Backgrounds
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm sunset gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ffb347 0%, #ffdbac 50%, #ffd699 100%)',
    previewColor: '#ffb347',
    category: 'gradient',
    emoji: '🌅',
  },
  {
    id: 'ocean-wave',
    name: 'Ocean Wave',
    description: 'Serene ocean gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%)',
    previewColor: '#667eea',
    category: 'gradient',
    emoji: '🌊',
  },
  {
    id: 'cotton-candy',
    name: 'Cotton Candy',
    description: 'Sweet pink-blue gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ffc0e3 0%, #c4a8ff 50%, #a3c5ff 100%)',
    previewColor: '#ffc0e3',
    category: 'gradient',
    emoji: '🍭',
  },
  {
    id: 'peach-dream',
    name: 'Peach Dream',
    description: 'Warm peach gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ffd89b 0%, #ffb6a3 50%, #ff9fb2 100%)',
    previewColor: '#ffd89b',
    category: 'gradient',
    emoji: '🍑',
  },
  {
    id: 'minty-fresh',
    name: 'Minty Fresh',
    description: 'Cool mint gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 50%, #fed6e3 100%)',
    previewColor: '#a8edea',
    category: 'gradient',
    emoji: '🌬️',
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    description: 'Rich golden gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #f6d5a8 0%, #f9a825 50%, #f97316 100%)',
    previewColor: '#f6d5a8',
    category: 'gradient',
    emoji: '✨',
  },

  // Pattern Backgrounds
  {
    id: 'polka-pink',
    name: 'Polka Pink',
    description: 'Pink with white polka dots',
    type: 'pattern',
    value: 'radial-gradient(circle, #ffffff 2px, transparent 2px), linear-gradient(0deg, #ffc0e3, #ffc0e3)',
    previewColor: '#ffc0e3',
    category: 'pattern',
    emoji: '⚪',
  },
  {
    id: 'checkerboard',
    name: 'Checkerboard',
    description: 'Classic checkerboard pattern',
    type: 'pattern',
    value: 'linear-gradient(45deg, #e0e0e0 25%, transparent 25%, transparent 75%, #e0e0e0 75%, #e0e0e0), linear-gradient(45deg, #e0e0e0 25%, transparent 25%, transparent 75%, #e0e0e0 75%, #e0e0e0), linear-gradient(#f5f5f5, #f5f5f5)',
    previewColor: '#f5f5f5',
    category: 'pattern',
    emoji: '🏁',
  },
  {
    id: 'diagonal-stripes',
    name: 'Diagonal Stripes',
    description: 'Soft diagonal stripes',
    type: 'pattern',
    value: 'repeating-linear-gradient(45deg, #f0e6ff, #f0e6ff 10px, #e6d9ff 10px, #e6d9ff 20px)',
    previewColor: '#f0e6ff',
    category: 'pattern',
    emoji: '🎀',
  },
  {
    id: 'wavy-lines',
    name: 'Wavy Lines',
    description: 'Subtle wavy pattern',
    type: 'pattern',
    value: 'linear-gradient(0deg, rgba(200,220,196,0.3) 0%, transparent 50%, rgba(200,220,196,0.3) 100%)',
    previewColor: '#f0f8f0',
    category: 'pattern',
    emoji: '〰️',
  },

  // Vibrant Backgrounds
  {
    id: 'neon-pink',
    name: 'Neon Pink',
    description: 'Bright electric pink',
    type: 'solid',
    value: '#ff006e',
    previewColor: '#ff006e',
    category: 'vibrant',
    emoji: '💖',
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    description: 'Vibrant neon blue',
    type: 'solid',
    value: '#00d9ff',
    previewColor: '#00d9ff',
    category: 'vibrant',
    emoji: '⚡',
  },
  {
    id: 'lime-green',
    name: 'Lime Green',
    description: 'Bright lime accent',
    type: 'solid',
    value: '#39ff14',
    previewColor: '#39ff14',
    category: 'vibrant',
    emoji: '💚',
  },
  {
    id: 'hot-orange',
    name: 'Hot Orange',
    description: 'Fiery orange',
    type: 'solid',
    value: '#ff6b35',
    previewColor: '#ff6b35',
    category: 'vibrant',
    emoji: '🔥',
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    description: 'Deep royal purple',
    type: 'solid',
    value: '#7209b7',
    previewColor: '#7209b7',
    category: 'vibrant',
    emoji: '👑',
  },
  {
    id: 'cyber-gradient',
    name: 'Cyber',
    description: 'Neon cyber gradient',
    type: 'gradient',
    value: 'linear-gradient(135deg, #ff006e 0%, #00d9ff 50%, #39ff14 100%)',
    previewColor: '#ff006e',
    category: 'vibrant',
    emoji: '🌐',
  },
]
