import type { FrameTheme, ThemeCategory } from '@/types'

export const THEME_CATEGORIES: { id: ThemeCategory | 'all'; label: string }[] = [
  { id: 'all', label: 'Semua' },
  { id: 'neon', label: 'Neon' },
  { id: 'cute', label: 'Cute' },
  { id: 'film', label: 'Film' },
  { id: 'retro', label: 'Retro' },
  { id: 'minimal', label: 'Minimal' },
  { id: 'party', label: 'Party' },
  { id: 'elegant', label: 'Elegan' },
]

export const THEMES: FrameTheme[] = [
  {
    id: 'midnight',
    name: 'Midnight',
    description: 'Gelap dengan aksen neon pink',
    category: 'neon',
    previewColor: '#0a0a1a',
    accentColor: '#ff2d78',
    filterCSS: 'contrast(1.08) saturate(1.15)',
    borderStyle: '2px solid #ff2d78',
    backgroundColor: '#0a0a1a',
    textColor: '#ff6b9d',
    watermark: 'SNAPBOOTH',
    emoji: '🌙',
  },
  {
    id: 'cyber',
    name: 'Cyber',
    description: 'Matrix hijau futuristik',
    category: 'neon',
    previewColor: '#021a12',
    accentColor: '#00ff9d',
    filterCSS: 'saturate(1.2) contrast(1.1)',
    borderStyle: '2px solid #00ff9d',
    backgroundColor: '#021a12',
    textColor: '#00ff9d',
    watermark: 'CYBER',
    emoji: '💚',
  },
  {
    id: 'sakura',
    name: 'Sakura',
    description: 'Pink lembut ala Jepang',
    category: 'cute',
    previewColor: '#fce4ec',
    accentColor: '#e91e8c',
    filterCSS: 'saturate(1.08) brightness(1.04)',
    borderStyle: '2px solid #f48fb1',
    backgroundColor: '#fce4ec',
    textColor: '#880e4f',
    watermark: 'SAKURA',
    emoji: '🌸',
  },
  {
    id: 'candy',
    name: 'Candy Pop',
    description: 'Pastel manis & ceria',
    category: 'cute',
    previewColor: '#fff0f5',
    accentColor: '#ff80ab',
    filterCSS: 'brightness(1.06) saturate(1.25)',
    borderStyle: '2px solid #ff80ab',
    backgroundColor: '#fff0f5',
    textColor: '#c2185b',
    watermark: 'CANDY',
    emoji: '🍬',
  },
  {
    id: 'cherry',
    name: 'Cherry Blossom',
    description: 'Merah muda dreamy',
    category: 'cute',
    previewColor: '#2a0a14',
    accentColor: '#ff4d6d',
    filterCSS: 'saturate(1.15) brightness(1.02)',
    borderStyle: '2px solid #ff4d6d',
    backgroundColor: '#2a0a14',
    textColor: '#ffb3c1',
    watermark: 'CHERRY',
    emoji: '🍒',
  },
  {
    id: 'film35',
    name: '35mm Film',
    description: 'Vintage analog hangat',
    category: 'film',
    previewColor: '#1a1410',
    accentColor: '#d4a84b',
    filterCSS: 'sepia(0.35) contrast(1.1) brightness(0.92)',
    borderStyle: '2px solid #d4a84b',
    backgroundColor: '#1a1410',
    textColor: '#d4a84b',
    watermark: '35MM',
    emoji: '🎞️',
  },
  {
    id: 'noir',
    name: 'Film Noir',
    description: 'Drama hitam putih klasik',
    category: 'film',
    previewColor: '#111',
    accentColor: '#c0c0c0',
    filterCSS: 'grayscale(1) contrast(1.18)',
    borderStyle: '2px solid #666',
    backgroundColor: '#111',
    textColor: '#e8e8e8',
    watermark: 'NOIR',
    emoji: '🎬',
  },
  {
    id: 'polaroid',
    name: 'Polaroid',
    description: 'Krem hangat seperti cetak instan',
    category: 'film',
    previewColor: '#f5f0e8',
    accentColor: '#8b7355',
    filterCSS: 'sepia(0.15) brightness(1.03)',
    borderStyle: '2px solid #d4c4b0',
    backgroundColor: '#f5f0e8',
    textColor: '#5c4a3a',
    watermark: 'POLAROID',
    emoji: '📷',
  },
  {
    id: 'retro90',
    name: 'Retro 90s',
    description: 'Warna bold era VHS',
    category: 'retro',
    previewColor: '#1a0533',
    accentColor: '#00e5ff',
    filterCSS: 'saturate(1.35) contrast(1.08)',
    borderStyle: '2px solid #00e5ff',
    backgroundColor: '#1a0533',
    textColor: '#00e5ff',
    watermark: 'RETRO 90',
    emoji: '📺',
  },
  {
    id: 'vapor',
    name: 'Vaporwave',
    description: 'Ungu pink aesthetic 80an',
    category: 'retro',
    previewColor: '#1a0a2e',
    accentColor: '#ff71ce',
    filterCSS: 'saturate(1.3) hue-rotate(-8deg)',
    borderStyle: '2px solid #ff71ce',
    backgroundColor: '#1a0a2e',
    textColor: '#01cdfe',
    watermark: 'VAPOR',
    emoji: '🌴',
  },
  {
    id: 'sunset',
    name: 'Sunset',
    description: 'Oranye ungu golden hour',
    category: 'retro',
    previewColor: '#1f0f1a',
    accentColor: '#ff6b35',
    filterCSS: 'sepia(0.2) saturate(1.2) brightness(1.05)',
    borderStyle: '2px solid #ff6b35',
    backgroundColor: '#1f0f1a',
    textColor: '#ffb347',
    watermark: 'SUNSET',
    emoji: '🌅',
  },
  {
    id: 'clean',
    name: 'Clean White',
    description: 'Putih minimal timeless',
    category: 'minimal',
    previewColor: '#ffffff',
    accentColor: '#334155',
    filterCSS: 'none',
    borderStyle: '2px solid #e2e8f0',
    backgroundColor: '#ffffff',
    textColor: '#334155',
    watermark: 'SNAPBOOTH',
    emoji: '◻️',
  },
  {
    id: 'forest',
    name: 'Forest',
    description: 'Hijau alami tenang',
    category: 'minimal',
    previewColor: '#1a2e1a',
    accentColor: '#4caf50',
    filterCSS: 'saturate(0.95) hue-rotate(8deg)',
    borderStyle: '2px solid #4caf50',
    backgroundColor: '#1a2e1a',
    textColor: '#a5d6a7',
    watermark: 'FOREST',
    emoji: '🌿',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Biru teal menyegarkan',
    category: 'minimal',
    previewColor: '#0a1628',
    accentColor: '#38bdf8',
    filterCSS: 'saturate(1.1) brightness(1.02)',
    borderStyle: '2px solid #38bdf8',
    backgroundColor: '#0a1628',
    textColor: '#7dd3fc',
    watermark: 'OCEAN',
    emoji: '🌊',
  },
  {
    id: 'ice',
    name: 'Ice',
    description: 'Dingin biru muda elegan',
    category: 'minimal',
    previewColor: '#e8f4fc',
    accentColor: '#0ea5e9',
    filterCSS: 'brightness(1.05) saturate(0.9)',
    borderStyle: '2px solid #7dd3fc',
    backgroundColor: '#e8f4fc',
    textColor: '#0369a1',
    watermark: 'ICE',
    emoji: '❄️',
  },
  {
    id: 'party',
    name: 'Party',
    description: 'Warna-warni pesta malam',
    category: 'party',
    previewColor: '#1a0a2e',
    accentColor: '#fbbf24',
    filterCSS: 'saturate(1.4) contrast(1.05)',
    borderStyle: '2px solid #fbbf24',
    backgroundColor: '#1a0a2e',
    textColor: '#f472b6',
    watermark: 'PARTY',
    emoji: '🎉',
  },
  {
    id: 'gold',
    name: 'Gold Luxe',
    description: 'Hitam emas mewah',
    category: 'elegant',
    previewColor: '#0f0f0f',
    accentColor: '#d4af37',
    filterCSS: 'contrast(1.05) saturate(0.95)',
    borderStyle: '2px solid #d4af37',
    backgroundColor: '#0f0f0f',
    textColor: '#d4af37',
    watermark: 'LUXE',
    emoji: '✨',
  },
  {
    id: 'wedding',
    name: 'Wedding',
    description: 'Ivory romantis lembut',
    category: 'elegant',
    previewColor: '#faf8f5',
    accentColor: '#b8860b',
    filterCSS: 'brightness(1.04) saturate(0.92)',
    borderStyle: '2px solid #d4af37',
    backgroundColor: '#faf8f5',
    textColor: '#8b6914',
    watermark: 'FOREVER',
    emoji: '💍',
  },
  {
    id: 'lavender',
    name: 'Lavender',
    description: 'Ungu pastel dreamy',
    category: 'elegant',
    previewColor: '#1e1a2e',
    accentColor: '#b794f6',
    filterCSS: 'saturate(1.1) brightness(1.03)',
    borderStyle: '2px solid #b794f6',
    backgroundColor: '#1e1a2e',
    textColor: '#ddd6fe',
    watermark: 'DREAM',
    emoji: '💜',
  },
  {
    id: 'autumn',
    name: 'Autumn',
    description: 'Coklat oranye musim gugur',
    category: 'retro',
    previewColor: '#1c1208',
    accentColor: '#e85d04',
    filterCSS: 'sepia(0.25) saturate(1.15)',
    borderStyle: '2px solid #e85d04',
    backgroundColor: '#1c1208',
    textColor: '#faa307',
    watermark: 'AUTUMN',
    emoji: '🍂',
  },
]
